"""Shared dimensions from the Chapter 4 manuscript."""

ACTION_DIM = 6
ACTION_HORIZON = 16
ACTION_BINS = 256
ACTION_GRID = ACTION_HORIZON * ACTION_DIM
SMOLLM_VOCAB = 49_152
SMOLLM_WIDTH = 576
ACTION_TOKEN_BASE = SMOLLM_VOCAB - ACTION_BINS
